#######################################
# Pontificia Universidad Javeriana
# Autor: David Vallejo Giraldo
# Archivo: Autimatización de Proceso de Compilación
# Tema: Compilación Modular en C
########################################

GCC = gcc
FLAGS=
MODULO= modulo

PROGRAMAS= principal

principal:
	$(GCC) $(MODULO).c $@.c -o $@


clean:
	$(RM) $(PROGRAMAS)
