#######################################
#Autor: David Vallejo
#fichero: automatización de compilación
#######################################

GCC=gcc
FLAGS= -lm
MODULO = modulo

PROGRAMAS = principal

principal:
	$(GCC) $@.c $(MODULO).c -o $@ $(FLAGS)

clean:
	$(RM) $(PROGRAMAS)
